mode = wsgi
bind = "0.0.0.0:8080"
pidfile = "/home/box/web/gunicorn/gunicorn.pid"
accesslog = "/home/box/web/gunicorn/access.log"
errorlog = "/home/box/web/gunicorn/error.log"
working_dir = "/web"
workers = 4
timeout = 60
args='web.hello:wsgi_app'
